In [1]:
import numpy as np

# Q1. Basic arithmetic operations

arr1 = np.array([1, 2, 3, 0])
arr2 = np.array([4, 1, 0, 6])

print("Addition:", arr1 + arr2)
print("Subtraction:", arr1 - arr2)
print("Multiplication:", arr1 * arr2)
# Handle division by zero safely
with np.errstate(divide='ignore', invalid='ignore'):
    division_result = np.true_divide(arr1, arr2)
    division_result[~np.isfinite(division_result)] = np.nan
print("Division:", division_result)

Addition: [5 3 3 6]
Subtraction: [-3  1  3 -6]
Multiplication: [4 2 0 0]
Division: [0.25 2.    nan 0.  ]


In [2]:
# Q2. 1-D and 2-D random arrays

arr1d = np.random.randint(1, 101, 5)
arr2d = np.random.randint(1, 101, (4, 5))

print("\n1-D array:", arr1d)
print("2-D array:\n", arr2d)

print("Addition:\n", arr2d + arr1d)
print("Subtraction:\n", arr2d - arr1d)



1-D array: [61 81 87  4  1]
2-D array:
 [[90 75 84 55 46]
 [44 37 13 82 95]
 [33 76 17  7 56]
 [52 25 49 27 28]]
Addition:
 [[151 156 171  59  47]
 [105 118 100  86  96]
 [ 94 157 104  11  57]
 [113 106 136  31  29]]
Subtraction:
 [[ 29  -6  -3  51  45]
 [-17 -44 -74  78  94]
 [-28  -5 -70   3  55]
 [ -9 -56 -38  23  27]]


In [3]:
# Q3. 3-D array indexing/slicing
# -------------------------------
arr3d = np.random.randint(1, 101, (3, 3, 3))
print("\n3-D array:\n", arr3d)

print("Third column of second 2-D array:", arr3d[1, :, 2])
print("First and third row of first 2-D array:\n", arr3d[0, [0, 2], :])
print("Intersection of first row and third column in third 2-D array:", arr3d[2, 0, 2])



3-D array:
 [[[54 31 29]
  [14  8 95]
  [64 80 86]]

 [[25 18 64]
  [99 33 12]
  [32  6 56]]

 [[94 86 29]
  [39 37 40]
  [30 98 99]]]
Third column of second 2-D array: [64 12 56]
First and third row of first 2-D array:
 [[54 31 29]
 [64 80 86]]
Intersection of first row and third column in third 2-D array: 29


In [4]:
# Q4. 2-D array even/odd/sum/reshape

arr2d_q4 = np.random.randint(1, 101, (5, 4))
print("\nQ4 Array:\n", arr2d_q4)

print("Even numbers:", arr2d_q4[arr2d_q4 % 2 == 0])
print("Odd numbers:", arr2d_q4[arr2d_q4 % 2 != 0])
print("Row-wise sum:", arr2d_q4.sum(axis=1))
print("Column-wise sum:", arr2d_q4.sum(axis=0))

arr3d_q4 = arr2d_q4.reshape(2, 2, 5)
print("Reshaped 3-D array (2x2x5):\n", arr3d_q4)



Q4 Array:
 [[66 22 83 19]
 [45 34 87 33]
 [95 28 54 20]
 [35 81 72 73]
 [58 51 88 71]]
Even numbers: [66 22 34 28 54 20 72 58 88]
Odd numbers: [83 19 45 87 33 95 35 81 73 51 71]
Row-wise sum: [190 199 197 261 268]
Column-wise sum: [299 216 384 216]
Reshaped 3-D array (2x2x5):
 [[[66 22 83 19 45]
  [34 87 33 95 28]]

 [[54 20 35 81 72]
  [73 58 51 88 71]]]


In [5]:
import numpy as np
# Q5. Row/column swaps, replacement, reshape

arr2d_q5 = np.random.randint(1, 101, (5, 4))
print("\nQ5 Original Array:\n", arr2d_q5)

# Swap first and third row
arr2d_q5[[0, 2]] = arr2d_q5[[2, 0]]

# Swap second and fourth column
arr2d_q5[:, [1, 3]] = arr2d_q5[:, [3, 1]]

# Replace values less than 50 with zero
arr2d_q5[arr2d_q5 < 50] = 0

# Convert to 1-D array
arr1d_q5 = arr2d_q5.flatten()

print("Modified Array:\n", arr2d_q5)
print("Flattened 1-D Array:", arr1d_q5)




Q5 Original Array:
 [[81 89 42 30]
 [48 93 98 50]
 [ 8 67 69 79]
 [63 50 26 23]
 [71 72 97 79]]
Modified Array:
 [[ 0 79 69 67]
 [ 0 50 98 93]
 [81  0  0 89]
 [63  0  0 50]
 [71 79 97 72]]
Flattened 1-D Array: [ 0 79 69 67  0 50 98 93 81  0  0 89 63  0  0 50 71 79 97 72]


In [8]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Stacking (creates a new axis)
print("\nVertical Stack:\n", np.vstack((a, b)))
print("Horizontal Stack:\n", np.hstack((a, b)))

# Concatenation (joins along an existing axis)
print("Concatenate along axis 0:\n", np.concatenate((a, b), axis=0))
print("Concatenate along axis 1:\n", np.concatenate((a, b), axis=1))



Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]
Concatenate along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenate along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]
